import { CountryType } from '../models/Country';

export const france: CountryType = {
  name: {
    common: 'France',
    official: 'French Republic',
    nativeName: {
      fra: { official: 'République française', common: 'France' },
    },
  },
  tld: ['.fr'],
  cca2: 'FR',
  ccn3: '250',
  cca3: 'FRA',
  cioc: 'FRA',
  commonName: 'France',
  independent: true,
  status: 'officially-assigned',
  unMember: true,
  currencies: { EUR: { name: 'Euro', symbol: '€' } },
  capital: ['Paris'],
  altSpellings: ['FR', 'French Republic', 'République française'],
  region: 'Europe',
  subregion: 'Western Europe',
  languages: { fra: 'French' },
  latlng: [46, 2],
  borders: ['AND', 'BEL', 'DEU', 'ITA', 'LUX', 'MCO', 'ESP', 'CHE'],
  area: 551695,
  maps: {
    googleMaps: 'https://goo.gl/maps/g7QxxSFsWyTPKuzd7',
    openStreetMaps: 'https://www.openstreetmap.org/relation/1403916',
  },
  population: 67391582,
  timezones: [
    'UTC-10:00',
    'UTC-09:30',
    'UTC-09:00',
    'UTC-08:00',
    'UTC-04:00',
    'UTC-03:00',
    'UTC+01:00',
    'UTC+02:00',
    'UTC+03:00',
    'UTC+04:00',
    'UTC+05:00',
    'UTC+10:00',
    'UTC+11:00',
    'UTC+12:00',
  ],
  continents: ['Europe'],
  flags: {
    png: 'https://flagcdn.com/w320/fr.png',
    svg: 'https://flagcdn.com/fr.svg',
    alt: 'The flag of France is composed of three equal vertical bands of blue, white and red.',
  },
  coatOfArms: {
    png: 'https://mainfacts.com/media/images/coats_of_arms/fr.png',
    svg: 'https://mainfacts.com/media/images/coats_of_arms/fr.svg',
  },
  startOfWeek: 'monday',
  capitalInfo: { latlng: [48.87, 2.33] },
};
